### ISSUE TITLE
E474: Invalid argument after VIM update

### ISSUE THREAD

**Issue by skimmedtrollingcustard** [k4yt3x/ayu-vim-darker#2]
I use ayu-vim-darker with vim's built in package management. After updating to vim(gvim) 8.2.4651-1 I started receiving an error in the terminal and for a moment in vim when it initially starts:

> Error detected while processing /home/$USER/.vimrc[67]../home/$USER/.vim/pack/themes/start/ayu-vim-darker/colors/ayu.vim:
> line  275:
> E474: Invalid argument
> Press ENTER or type command to continue

The theme still seemed to work just fine otherwise. After commenting out line 275 the theme still functions but with no error. May not need this line anymore.

**Comment by k4yt3x** [comment]
Looks like our upstream has a fix for it: https://github.com/ayu-theme/ayu-vim/pull/72
I'll merge this ASAP.

**Comment by k4yt3x** [comment]
I just pushed the fix. Please check if it works.

**Comment by skimmedtrollingcustard** [comment]
Fix confirmed working, Thanks!
